from obsidian.core import Obsidian

note_body = """
contents of a note

link to [[Oura]]
link to Oura 

link to Spark

link to Apache Spark
"""

obsidian = Obsidian("~/obsidian-test")
obsidian.new_note(
    note_path='', 
    title="test_note", 
    body=note_body, 
    tags=["#autogenerated", "#test"],
    overwrite=True
    )
